### ISSUE TITLE
Error calling a dshell script from another dshell script

### ISSUE THREAD

**Issue by ram535** [bsutton/dshell#44]
```
dshell create script1.dart
dshell create script2.dart
```

Modify `script1.dart` to call `script2.dart'

```
'script2.dart'.run;
```

Throw this error:

```
Unhandled exception:
Invalid argument(s): Arguments is not a List: null
#0      new _ProcessImpl (dart:io-patch/process_patch.dart:248:7)
#1      Process.start (dart:io-patch/process_patch.dart:30:32)
#2      RunnableProcess.start (package:dshell/src/util/runnable_process.dart:62:24)
#3      Run.run (package:dshell/src/functions/run.dart:34:16)
#4      run (package:dshell/src/functions/run.dart:22:11)
#5      StringAsProcess.run (package:dshell/src/util/string_as_process.dart:32:19)
#6      main (file:///home/last/.dshell/cache/home/last/bin/scripts/script1.project/script1.dart:5:18)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by bsutton** [comment]
Fixed in 1.0.43.
