### ISSUE TITLE
Bad utf-8 readling pubspec annotation.

### ISSUE THREAD

**Issue by bsutton** [bsutton/dshell#83]
For the auditor project I compile the build script via

cd installer
dshell compile bin/build.dart

If I then run bin/build.dart the following error occurs:

```
bsutton@slayer4:~/git/auditor/installer$ bin/build -q
Building the auditor installer
Unhandled exception:
FormatException: Bad UTF-8 encoding 0xa6 (at offset 25)
#0      waitForEx (package:dshell/src/util/wait_for_ex.dart:41)
#1      PubSpecAnnotation._readLines (package:dshell/src/pubspec/pubspec_annotation.dart:130)
#2      new PubSpecAnnotation.fromScript (package:dshell/src/pubspec/pubspec_annotation.dart:30)
#3      Script.hasPubspecAnnotation (package:dshell/src/script/script.dart:151)
#4      Script.projectRoot (package:dshell/src/script/script.dart:178)
#5      main (file:///home/bsutton/git/auditor/installer/bin/build.dart:10)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168)

```

Is this because its still trying to load the pubspec annotation from the compiled exe which of course is a binary?

**Comment by bsutton** [comment]
Fixed in 1.10.9.
